(function(){
  const MAIN='https://9e507bq9nsow4n57d9tap0ohpd.hop.clickbank.net';
  const EXTRA='https://f21555c3kvj-1zc-zxjkslrl96.hop.clickbank.net';
  function isArticle(){return location.pathname.indexOf('/posts-ai/')===0||!!document.querySelector('.article-body,.post-body,.article-container');}
  function pick(){const t=(document.title+' '+document.body.innerText).toLowerCase();if(t.includes('تصميم')||t.includes('canva')||t.includes('midjourney')||t.includes('dall'))return{u:EXTRA,k:'🎨 عرض التصميم المناسب',b:'جرّب أداة التصميم'};if(t.includes('أفلييت')||t.includes('عمولة')||t.includes('أرباح'))return{u:EXTRA,k:'💰 عرض يساعدك على زيادة الأرباح',b:'احصل على العرض'};if(t.includes('أتمتة')||t.includes('إنتاجية')||t.includes('مهام'))return{u:MAIN,k:'⚡ عرض أتمتة المهام',b:'ابدأ أتمتة عملك'};if(t.includes('seo')||t.includes('جوجل')||t.includes('محتوى'))return{u:MAIN,k:'🚀 عرض المحتوى والـ SEO',b:'جرّب أداة المحتوى'};return{u:MAIN,k:'🔥 العرض المقترح',b:'جرّب الآن'};}
  function style(){if(document.getElementById('conversion-booster-style'))return;const s=document.createElement('style');s.id='conversion-booster-style';s.textContent='.sticky-profit-bar{position:fixed;left:12px;right:12px;bottom:12px;z-index:9999;background:#071426;color:#fff;border:1px solid rgba(255,255,255,.16);border-radius:18px;padding:.75rem 1rem;display:flex;align-items:center;justify-content:space-between;gap:.8rem;box-shadow:0 16px 38px rgba(0,0,0,.28)}.sticky-profit-bar strong{font-size:.95rem}.sticky-profit-bar a{background:#ea580c;color:#fff;border-radius:999px;padding:.55rem .9rem;font-weight:900;white-space:nowrap}.sticky-profit-bar button{background:transparent;color:#fff;border:0;font-size:1.1rem;cursor:pointer}.comparison-profit-box{margin:2rem 0;padding:1.2rem;border-radius:22px;background:#f8fafc;border:1px solid #d9e4f2}.comparison-profit-box h2{margin-top:0}.comparison-profit-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:.8rem}.comparison-profit-card{background:#fff;border:1px solid #e2e8f0;border-radius:18px;padding:1rem}.comparison-profit-card a{display:inline-block;margin-top:.7rem;background:#ea580c;color:#fff;border-radius:999px;padding:.55rem .9rem;font-weight:900}@media(max-width:700px){.sticky-profit-bar{font-size:.85rem}.comparison-profit-grid{grid-template-columns:1fr}}';document.head.appendChild(s);}
  function container(){return document.querySelector('.article-body,.post-body,.article-container,main article,main .container');}
  function addSticky(){if(!isArticle()||document.querySelector('.sticky-profit-bar'))return;const o=pick();const bar=document.createElement('div');bar.className='sticky-profit-bar';bar.innerHTML='<strong>'+o.k+'</strong><a href="'+o.u+'" target="_blank" rel="nofollow sponsored noopener noreferrer">'+o.b+'</a><button aria-label="إغلاق">×</button>';bar.querySelector('button').onclick=function(){bar.remove();};document.body.appendChild(bar);}
  function addComparison(){if(!isArticle()||document.querySelector('.comparison-profit-box'))return;const c=container();if(!c)return;const o=pick();const box=document.createElement('section');box.className='comparison-profit-box';box.innerHTML='<h2>قارن قبل أن تختار</h2><div class="comparison-profit-grid"><div class="comparison-profit-card"><h3>الخيار الأساسي</h3><p>مناسب لتطبيق فكرة المقال بسرعة والبدء بنتيجة عملية.</p><a href="'+o.u+'" target="_blank" rel="nofollow sponsored noopener noreferrer">'+o.b+'</a></div><div class="comparison-profit-card"><h3>بديل مفيد</h3><p>راجع قائمة الأدوات إذا أردت مقارنة أكثر من خيار قبل القرار.</p><a href="/best-ai-tools.html">قارن أدوات AI</a></div></div>';const ps=c.querySelectorAll('p');if(ps.length>4)ps[3].after(box);else c.appendChild(box);}
  function init(){style();addComparison();addSticky();}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else init();
})();
