(function(){
  function base(path){return path.startsWith('/') ? path : '/' + path;}
  function style(){
    if(document.getElementById('smart-footer-full-style'))return;
    const s=document.createElement('style');
    s.id='smart-footer-full-style';
    s.textContent=`
.smart-final-footer{background:linear-gradient(180deg,#071d35 0%,#041326 100%)!important;color:#fff!important;padding:0!important;margin-top:52px!important;border-top:1px solid rgba(255,255,255,.1)!important;overflow:hidden!important;direction:rtl!important;text-align:right!important}
.smart-final-footer *{box-sizing:border-box!important}.smart-final-footer a{text-decoration:none!important}.smart-final-footer .container{max-width:1180px!important;margin:0 auto!important;padding-left:22px!important;padding-right:22px!important;width:100%!important}
.smart-footer-cta{background:linear-gradient(135deg,rgba(234,88,12,.96),rgba(245,158,11,.9))!important;border:1px solid rgba(255,255,255,.18)!important;border-radius:24px!important;padding:22px 24px!important;margin:32px auto 24px!important;display:flex!important;align-items:center!important;justify-content:space-between!important;gap:18px!important;box-shadow:0 18px 45px rgba(0,0,0,.18)!important}.smart-footer-cta h2{margin:0 0 8px!important;color:#fff!important;font-size:1.35rem!important;line-height:1.35!important}.smart-footer-cta p{margin:0!important;color:#fff7ed!important;line-height:1.7!important}.smart-footer-cta-actions{display:flex!important;gap:10px!important;flex-wrap:wrap!important;justify-content:flex-end!important}.smart-footer-cta a{display:inline-flex!important;align-items:center!important;justify-content:center!important;min-height:42px!important;padding:.65rem 1.05rem!important;border-radius:999px!important;font-weight:900!important;white-space:nowrap!important}.smart-footer-cta-primary{background:#fff!important;color:#9a3412!important}.smart-footer-cta-secondary{background:rgba(7,29,53,.22)!important;color:#fff!important;border:1px solid rgba(255,255,255,.28)!important}
.smart-footer-main{display:grid!important;grid-template-columns:1.1fr 2.2fr!important;gap:34px!important;align-items:start!important;padding:12px 0 32px!important}.smart-footer-brand h2{margin:0 0 10px!important;color:#fff!important;font-size:1.7rem!important}.smart-footer-brand p{color:#cbd5e1!important;line-height:1.9!important;margin:.4rem 0!important;max-width:390px!important}.smart-footer-contact{margin-top:12px!important;color:#fff!important;font-weight:800!important}.smart-footer-contact a{color:#fed7aa!important;overflow-wrap:anywhere!important}.smart-footer-badges{display:flex!important;gap:8px!important;flex-wrap:wrap!important;margin-top:14px!important}.smart-footer-badge{display:inline-flex!important;padding:.42rem .7rem!important;border-radius:999px!important;background:rgba(234,88,12,.18)!important;color:#fed7aa!important;font-weight:900!important;border:1px solid rgba(251,146,60,.25)!important;font-size:.86rem!important}
.smart-footer-links{display:flex!important;flex-direction:column!important;gap:18px!important}.smart-footer-row{display:grid!important;grid-template-columns:130px 1fr!important;gap:14px!important;align-items:start!important;padding-bottom:16px!important;border-bottom:1px solid rgba(255,255,255,.09)!important}.smart-footer-row:last-child{border-bottom:0!important;padding-bottom:0!important}.smart-footer-row h3{color:#fff!important;margin:0!important;font-size:1rem!important;position:relative!important;padding-bottom:10px!important;white-space:nowrap!important}.smart-footer-row h3:after{content:""!important;position:absolute!important;right:0!important;bottom:0!important;width:42px!important;height:3px!important;border-radius:999px!important;background:#ea580c!important}.smart-footer-row nav{display:flex!important;flex-direction:row!important;gap:9px!important;align-items:center!important;justify-content:flex-start!important;flex-wrap:wrap!important}.smart-footer-row a{display:inline-flex!important;align-items:center!important;justify-content:center!important;gap:6px!important;color:#dbeafe!important;background:rgba(255,255,255,.055)!important;border:1px solid rgba(255,255,255,.09)!important;border-radius:999px!important;font-weight:800!important;font-size:.92rem!important;line-height:1.45!important;padding:8px 12px!important;transition:color .18s ease,background .18s ease,transform .18s ease!important;white-space:nowrap!important}.smart-footer-row a:hover{color:#fff!important;background:rgba(234,88,12,.28)!important;transform:translateY(-1px)!important}.smart-footer-row a:before{content:"›"!important;color:#fb923c!important;font-weight:900!important;font-size:1.05rem!important;line-height:1!important}
.smart-footer-bottom{border-top:1px solid rgba(255,255,255,.12)!important;padding:16px 0 18px!important;display:flex!important;justify-content:space-between!important;align-items:center!important;gap:12px!important;flex-wrap:wrap!important;color:#cbd5e1!important;font-size:.9rem!important}.smart-footer-bottom-links{display:flex!important;gap:10px!important;flex-wrap:wrap!important}.smart-footer-bottom-links a{color:#cbd5e1!important;font-weight:800!important;background:rgba(255,255,255,.055)!important;border-radius:999px!important;padding:6px 10px!important}.smart-footer-bottom-links a:hover{color:#fff!important}
@media(max-width:980px){.smart-footer-main{grid-template-columns:1fr!important;gap:24px!important}.smart-footer-brand p{max-width:none!important}.smart-footer-cta{align-items:flex-start!important;flex-direction:column!important}.smart-footer-cta-actions{justify-content:flex-start!important}.smart-footer-bottom{justify-content:center!important;text-align:center!important}.smart-footer-bottom-links{justify-content:center!important}}
@media(max-width:620px){.smart-final-footer .container{padding-left:14px!important;padding-right:14px!important}.smart-footer-cta{margin-top:22px!important;border-radius:22px!important;padding:18px!important;text-align:center!important;align-items:center!important}.smart-footer-cta-actions{justify-content:center!important;width:100%!important}.smart-footer-cta a{width:100%!important}.smart-footer-brand{text-align:center!important}.smart-footer-brand p{margin-left:auto!important;margin-right:auto!important}.smart-footer-badges{justify-content:center!important}.smart-footer-row{grid-template-columns:1fr!important;gap:12px!important;background:rgba(255,255,255,.045)!important;border:1px solid rgba(255,255,255,.08)!important;border-radius:18px!important;padding:14px!important}.smart-footer-row nav{justify-content:center!important}.smart-footer-row h3{text-align:center!important}.smart-footer-row h3:after{right:50%!important;transform:translateX(50%)!important}.smart-footer-row a{font-size:.88rem!important;padding:8px 10px!important}.smart-footer-bottom{flex-direction:column!important;align-items:center!important}}
    `;
    document.head.appendChild(s);
  }
  function footerHTML(){
    return '<div class="container smart-footer-cta">'+
      '<div><h2>ابدأ من المكان الصحيح</h2><p>اختر مقالة، قارن الأدوات، أو انتقل مباشرة إلى مسار تعلم AI.</p></div>'+
      '<div class="smart-footer-cta-actions"><a class="smart-footer-cta-primary" href="'+base('articles.html')+'">📖 كل المقالات</a><a class="smart-footer-cta-secondary" href="'+base('ai-tools-comparison.html')+'">⚖️ مقارنة الأدوات</a></div>'+
      '</div>'+
      '<div class="container smart-footer-main">'+
      '<div class="smart-footer-brand"><h2>smartafiliate</h2><p>منصة عربية عملية لفهم الذكاء الاصطناعي، أدوات AI، التسويق بالعمولة، وبناء محتوى قابل للنمو.</p><p class="smart-footer-contact">Contact: <a href="mailto:info@smartafiliate.com">info@smartafiliate.com</a></p><div class="smart-footer-badges"><span class="smart-footer-badge">AI Tools</span><span class="smart-footer-badge">Affiliate</span><span class="smart-footer-badge">SEO</span></div></div>'+
      '<div class="smart-footer-links">'+
      '<div class="smart-footer-row"><h3>عن الموقع</h3><nav><a href="'+base('about.html')+'">من نحن</a><a href="'+base('about.html')+'">About me</a><a href="'+base('contact.html')+'">تواصل معنا</a><a href="'+base('disclosure.html')+'">الإفصاح</a></nav></div>'+
      '<div class="smart-footer-row"><h3>المحتوى</h3><nav><a href="'+base('articles.html')+'">كل المقالات</a><a href="'+base('ai-articles.html')+'">مكتبة AI</a><a href="'+base('posts-ai.html')+'">فهرس مقالات AI</a><a href="'+base('blog.html')+'">المدونة</a></nav></div>'+
      '<div class="smart-footer-row"><h3>التعلم والأدوات</h3><nav><a href="'+base('best-ai-tools.html')+'">أفضل أدوات AI</a><a href="'+base('ai-tools-comparison.html')+'">مقارنة الأدوات</a><a href="'+base('learn-ai.html')+'">تعلم AI</a><a href="'+base('open-source.html')+'">مصادر مفتوحة</a></nav></div>'+
      '<div class="smart-footer-row"><h3>القوانين</h3><nav><a href="'+base('privacy.html')+'">سياسة الخصوصية</a><a href="'+base('privacy-policy.html')+'">Privacy Policy</a><a href="'+base('cookie-policy.html')+'">سياسة الكوكيز</a><a href="'+base('terms.html')+'">الشروط والأحكام</a><a href="'+base('sitemap.html')+'">خريطة الموقع</a></nav></div>'+
      '</div></div><div class="container smart-footer-bottom"><span>smartafiliate © 2026 — جميع الحقوق محفوظة</span><div class="smart-footer-bottom-links"><a href="'+base('index.html')+'">الرئيسية</a><a href="'+base('contact.html')+'">تواصل</a><a href="'+base('sitemap.xml')+'">Sitemap XML</a></div></div>';
  }
  function build(){
    style();
    document.querySelectorAll('footer,.site-footer,.smart-global-footer,.smart-final-footer,.smart-global-contact').forEach(function(f){f.remove();});
    var footer=document.createElement('footer');
    footer.className='smart-final-footer';
    footer.innerHTML=footerHTML();
    var main=document.querySelector('main');
    if(main)main.insertAdjacentElement('afterend',footer);else document.body.appendChild(footer);
  }
  function run(){build();setTimeout(build,1000);}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',run,{once:true});else run();
})();
